package io.github.noahdbyers.roguelite;

public enum ItemId {
    BANANA,
    HOLY_PENDANT,
    CROWN_OF_THE_FALLEN_KING,
    MANTLE_OF_THE_SWIFT_HUNTRESS,
    SPEARHEAD_OF_THE_SKYBREAKER,
    PENDANT_OF_THE_LAST_TRUE_ORACLE,
    SCROLL_OF_THE_FALLEN_HEROES,
    TABLET_OF_THE_NINE_TRIALS,
    GLYPH_OF_THE_TWIN_SUNS,
    INK_OF_THE_FORGOTTEN_SCRIBE,
    ASTRAL_ANCHOR,
    INCENSE_OF_THE_QUIET_SPIRIT,
    BLESSED_ASH,
    PRAYER_STONE,
    JESTERS_DICE,
    EMBER_OF_THE_FLAMING_HERO,
    TEAR_OF_THE_VEILED_SAINT,
    MOON_GODS_BLESSING,
    SUN_GODS_BLESSING,
    TRUE_GODS_BLESSING
}
